'use strict'

module.exports = {
  accept: ['Live',
    'festival',
    'fest',
    'live',
    'filmed',
    'recorded',
    'tour',
    'venue',
    'official HD Live Video',
    'Official Music Video Live',
    'perform',
    'performance video',
    'Vevo Summer Sets',
    'performing',
    'concert',
    'full concert',
    'full set',
    'live set',
    'live concerts',
    'live performance',
    'show completo',
    'live studio session',
    'live sessions',
    'sessions',
    'wembly',
    'studio recordings',
    'Lollapalooza',
    'nightclub',
    'full show',
    'Glastonbury',
    'Rock am Ring',
    'Roskilde',
    'Electric Love',
    'Ziggo Dome',
    'Group Therapy',
    'EDC',
    'Coachella',
    'Tommorowland',
    'TommorowWorld',
    'Stereosonic',
    'Burning Man',
    'Ultra',
    'Sunburn',
    'Live Lounge',
    'Gdansk',
    'Royal Albert Hall',
    'Boiler Room',
    'Red Rocks',
    'Defqon.1',
    'Rock in Rio',
    'video ao vivo',
    'en vivo',
    'show completo',
    'on Air']
}
