'use strict'

module.exports = {
  accept: ['Live',
    'festival',
    'fest',
    'live',
    'filmed',
    'concierto',
    'recorded',
    'tour',
    'venue',
    'official HD Live Video',
    'Official Music Video Live',
    'perform',
    'performance video',
    'Vevo Summer Sets',
    'performing',
    'concert',
    'концерт',
    'ライブ',
    'full concert',
    'best concert',
    'rock concert',
    'in concert',
    'full set',
    'live set',
    'live dj set',
    'live concert',
    'live concert 2017',
    'live concert 2016',
    'live concerts',
    'koncert',
    'คอนเสิร์ต',
    'conciertos',
    'live performance',
    'show completo',
    'live studio session',
    'live session',
    'sessions',
    'wembly',
    'studio recording',
    'studio recording session',
    'Lollapalooza',
    'nightclub',
    'full show',
    'Glastonbury',
    'Rock am Ring',
    'Roskilde',
    'Electric Love',
    'Ziggo Dome',
    'Group Therapy',
    'EDC',
    'Coachella',
    'Tommorowland',
    'TommorowWorld',
    'Primavera',
    'Stereosonic',
    'Burning Man',
    'Ultra',
    'Sunburn',
    'Live Lounge',
    'Gdansk',
    'Royal Albert Hall',
    'Boiler Room',
    'Red Rocks',
    'Defqon.1',
    'Rock in Rio',
    'video ao vivo',
    'en vivo',
    'show completo',
    'on Air']
}
