'use strict'

module.exports = {
  accept: ['festival',
    'fest',
    'live',
    'venue',
    'perform',
    'concert',
    'full set',
    'live set',
    'live studio session',
    'live sessions',
    'studio recordings',
    'Lollapalooza',
    'nightclub',
    'full show',
    'Glastonbury',
    'Electric Love',
    'Ziggo Dome',
    'Group Therapy',
    'EDC',
    'Coachella',
    'Tommorowland',
    'TommorowWorld',
    'Ultra',
    'Sunburn',
    'Live Lounge',
    'Gdansk',
    'Royal Albert Hall',
    'Boiler Room',
    'Red Rocks',
    'Defqon.1',
    'Rock in Rio',
    'video ao vivo',
    'en vivo',
    'show completo',
    'on Air']
}
