/**
 * Created by rprat on 26-07-2017.
 */
'use strict'

module.exports = {
  reject: ['lyrics',
    'interview',
    'official video',
    'music video',
    'musicvideo',
    'best music video',
    'official music video',
    'extended mix',
    'lyric video',
    'official lyric video',
    'fan',
    'teaser',
    'trailer',
    'official trailer',
    'promotion',
    'promo',
    'preview',
    'cover',
    'acoustic cover',
    'drum cover',
    'guitar cover',
    'piano cover',
    'cover songs',
    'bass cover',
    'best cover',
    'fan made video',
    'fan video',
    'fan song',
    'official audio',
    'facebook',
    'instagram',
    'insta',
    'fb',
    'audio video',
    'audio',
    'audio latino',
    'audio song',
    'aftermovie',
    'after movie']
}
