'use strict'

module.exports = {
  genres: {
    Classical: ['classical'],
    Folk: ['folk'],
    Indie: ['indie', 'indie-pop'],
    HipdashHop: ['hip-hop', 'groove', 'trip-hop'],
    AltdashRock: ['alt-rock', 'grunge'],
    Rock: ['alternative', 'emo', 'goth', 'guitar', 'hard-rock', 'hardcore', 'industrial', 'j-rock', 'psych-rock', 'punk', 'punk-rock', 'rock', 'rock-n-roll', 'rockabilly'],
    Metal: ['black-metal', 'death-metal', 'grindcore', 'groove', 'heavy-metal', 'metal', 'metal-misc', 'metalcore'],
    Country: ['country', 'honky-tonk', 'rockabilly', 'romance', 'sad', 'singer-songwriter', 'songwriter'],
    Ambient: ['chill', 'ambient', 'romance', 'sad', 'rainy-day', 'sleep', 'soul', 'study', 'summer'],
    Pop: ['cantopop', 'mandopop', 'j-pop', 'k-pop', 'pop', 'pop-film', 'power-pop', 'romance', 'sad', 'synth-pop'],
    JazzAndBlues: ['afrobeat', 'bluegrass', 'blues', 'funk', 'groove', 'jazz'],
    World: ['work-out', 'bossanova', 'brazil', 'turkish', 'swedish', 'mpb', 'spanish', 'pagode', 'philippines-opm', 'british', 'forro', 'french', 'german', 'indian', 'iranian', 'j-dance', 'j-idol', 'j-pop', 'j-rock', 'k-pop', 'latin', 'latino', 'malay', 'salsa', 'samba', 'sertanejo'],
    DanceAndEDM: ['breakbeat', 'chicago-house', 'club', 'trance', 'progressive-house', 'tango', 'party', 'dance', 'dancehall', 'deep-house', 'disco', 'j-dance', 'drum-and-bass', 'edm', 'electro', 'garage', 'hardstyle', 'house'],
    Techno: ['detroit-techno', 'minimal-techno', 'techno'],
    Dubstep: ['dub', 'dubstep', 'post-dubstep'],
    Reggae: ['groove', 'reggae', 'reggaeton'],
    RAndB: ['groove', 'r-n-b', 'ska'],
    Electronic: ['electronic', 'idm', 'industrial', 'romance'],
    Acoustic: ['acoustic', 'romance', 'sad'],
    OperaAndPiano: ['opera', 'piano'],
    Other: ['anime', 'children', 'comedy', 'disney', 'gospel', 'work-out', 'soundtracks', 'happy', 'holidays', 'kids', 'movies', 'new-age', 'new-release', 'road-trip', 'show-tunes']
  },
  spotifyGenres: {
    All: ['acoustic',
      'afrobeat',
      'alt-rock',
      'alternative',
      'ambient',
      'anime',
      'black-metal',
      'bluegrass',
      'blues',
      'bossanova',
      'brazil',
      'breakbeat',
      'british',
      'cantopop',
      'chicago-house',
      'children',
      'chill',
      'classical',
      'club',
      'comedy',
      'country',
      'dance',
      'dancehall',
      'death-metal',
      'deep-house',
      'detroit-techno',
      'disco',
      'disney',
      'drum-and-bass',
      'dub',
      'dubstep',
      'edm',
      'electro',
      'electronic',
      'emo',
      'folk',
      'forro',
      'french',
      'funk',
      'garage',
      'german',
      'gospel',
      'goth',
      'grindcore',
      'groove',
      'grunge',
      'guitar',
      'happy',
      'hard-rock',
      'hardcore',
      'hardstyle',
      'heavy-metal',
      'hip-hop',
      'holidays',
      'honky-tonk',
      'house',
      'idm',
      'indian',
      'indie',
      'indie-pop',
      'industrial',
      'iranian',
      'j-dance',
      'j-idol',
      'j-pop',
      'j-rock',
      'jazz',
      'k-pop',
      'kids',
      'latin',
      'latino',
      'malay',
      'mandopop',
      'metal',
      'metal-misc',
      'metalcore',
      'minimal-techno',
      'movies',
      'mpb',
      'new-age',
      'new-release',
      'opera',
      'pagode',
      'party',
      'philippines-opm',
      'piano',
      'pop',
      'pop-film',
      'post-dubstep',
      'power-pop',
      'progressive-house',
      'psych-rock',
      'punk',
      'punk-rock',
      'r-n-b',
      'rainy-day',
      'reggae',
      'reggaeton',
      'road-trip',
      'rock',
      'rock-n-roll',
      'rockabilly',
      'romance',
      'sad',
      'salsa',
      'samba',
      'sertanejo',
      'show-tunes',
      'singer-songwriter',
      'ska',
      'sleep',
      'songwriter',
      'soul',
      'soundtracks',
      'spanish',
      'study',
      'summer',
      'swedish',
      'synth-pop',
      'tango',
      'techno',
      'trance',
      'trip-hop',
      'turkish',
      'work-out',
      'world-music']
  }
}
